/* tslint:disable */
/* eslint-disable */
/**
 * audioserve API
 * REST API for audioserve
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AudioFile } from './AudioFile';
import {
    AudioFileFromJSON,
    AudioFileFromJSONTyped,
    AudioFileToIdFromJSON,
    AudioFileToJSON,
} from './AudioFile';
import type { PositionShort } from './PositionShort';
import {
    PositionShortFromJSON,
    PositionShortFromJSONTyped,
    PositionShortToJSON,
} from './PositionShort';
import type { Subfolder } from './Subfolder';
import {
    SubfolderFromJSON,
    SubfolderFromJSONTyped,
    SubfolderToJSON,
} from './Subfolder';
import type { TypedFile } from './TypedFile';
import {
    TypedFileFromJSON,
    TypedFileFromJSONTyped,
    TypedFileToJSON,
} from './TypedFile';

/**
 * 
 * @export
 * @interface AudioFolder
 */
export interface AudioFolder {
    /**
     * Is virtual folder - e.g. representing big chapterized file (.m4b etc.)
     * @type {boolean}
     * @memberof AudioFolder
     */
    isFile?: boolean;
    /**
     * last modification timestamp (unix time in miliseconds)
     * @type {number}
     * @memberof AudioFolder
     */
    modified?: number;
    /**
     * Total playback time of the audiofolder in seconds
     * @type {number}
     * @memberof AudioFolder
     */
    totalTime?: number;
    /**
     * 
     * @type {Array<AudioFile>}
     * @memberof AudioFolder
     */
    files?: Map<number, AudioFile>;
    
    subfolders?: Array<Subfolder>;
    /**
     * 
     * @type {TypedFile}
     * @memberof AudioFolder
     */
    cover?: TypedFile | null;
    /**
     * 
     * @type {TypedFile}
     * @memberof AudioFolder
     */
    description?: TypedFile | null;
    /**
     * Metadata tags for this folders - map of name to value
     * @type {object}
     * @memberof AudioFolder
     */
    tags?: object | null;
}

/**
 * Check if a given object implements the AudioFolder interface.
 */
export function instanceOfAudioFolder(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AudioFolderFromJSON(json: any): AudioFolder {
    return AudioFolderFromJSONTyped(json, false);
}

export function AudioFolderFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioFolder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isFile': !exists(json, 'is_file') ? undefined : json['is_file'],
        'modified': !exists(json, 'modified') ? undefined : json['modified'],
        'totalTime': !exists(json, 'total_time') ? undefined : json['total_time'],
        'files': !exists(json, 'files') ? undefined : new Map((json['files'] as Array<any>).map(AudioFileToIdFromJSON)),
        'subfolders': !exists(json, 'subfolders') ? undefined : (json['subfolders'] as Array<any>).map(SubfolderFromJSON),
        'cover': !exists(json, 'cover') ? undefined : TypedFileFromJSON(json['cover']),
        'description': !exists(json, 'description') ? undefined : TypedFileFromJSON(json['description']),
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
    };
}
